### ISSUE TITLE
Dangling VF's

### ISSUE THREAD

**Issue by tkekan** [att/vfd#124]
After the deletion of heat stack, the json files were no longer present in the vfd/config directory. 
But the 'iplex show all' still showed the VF's in the output in 'DOWN' state.

And below is the vfd output that states it failed due to the below check:

https://github.com/att/vfd/blob/9e7214d3c3df731d5c1c1cf3ca52f79e2020a5be/src/vfd/vfd_rif.c#L749

So changing that condition to vfc->vfid < 0 should solve this?

----------
Vfd.log
----------
1487015211 2017/02/13 19:46:51Z [1] deleting vf from file: /var/lib/vfd/config/94d61f92-2c4b-436d-baaf-6a416557ae8d.json
1487015211 2017/02/13 19:46:51Z [2] del: config data: name: Instance_admin-vmx-contrail-1_fpc0/94d61f92-2c4b-436d-baaf-6a416557ae8d
1487015211 2017/02/13 19:46:51Z [2] del: config data: pciid: 0000:02:00.0
1487015211 2017/02/13 19:46:51Z [2] del: config data: vfid: 0
1487015211 2017/02/13 19:46:51Z [1] vfd_del_vf failed: unable to read config file: /var/lib/vfd/config/94d61f92-2c4b-436d-baaf-6a416557ae8d.json
1487015211 2017/02/13 19:46:51Z [2] sending response: /tmp/IPLEX_32497(23) [1] 173 bytes
1487015211 2017/02/13 19:46:51Z [2] response written to pipe
1487015213 2017/02/13 19:46:53Z [2] raw message: ({"action": "delete", "params": {"loglevel": 0, "resource": null, "r_fifo": "/tmp/IPLEX_32500", "filename": "/var/lib/vfd/config/d5e5cac4-14e9-463c-8639-f854488a360a.json"}}
)
1487015213 2017/02/13 19:46:53Z [1] deleting vf from file: /var/lib/vfd/config/d5e5cac4-14e9-463c-8639-f854488a360a.json
1487015213 2017/02/13 19:46:53Z [2] del: config data: name: Instance_admin-vmx-contrail-1_fpc0/d5e5cac4-14e9-463c-8639-f854488a360a
1487015213 2017/02/13 19:46:53Z [2] del: config data: pciid: 0000:02:00.1
1487015213 2017/02/13 19:46:53Z [2] del: config data: vfid: 0
1487015213 2017/02/13 19:46:53Z [1] vfd_del_vf failed: unable to read config file: /var/lib/vfd/config/d5e5cac4-14e9-463c-8639-f854488a360a.json

**Comment by tkekan** [comment]
@ScottDaniels : Is this the reason for incorrect cleanup ?

**Comment by ScottDaniels** [comment]
Yes, good catch.  This is now fixed in commit 0c7c17daf5181421f88a0e26599c488c5b0c5cc3 (2016/02/14).   The range check was not correct after the change which allowed the minimum VF to be 0.
