### ISSUE TITLE
[FR] Configure VF to VF mirroring

### ISSUE THREAD

**Issue by pcarver** [att/vfd#129]
Add a feature to configure mirroring of traffic from one VF to another. It should be possible to specify a VF to mirror and a list of VLAN tags on that VF. An output VF and optionally VLAN tag must also be specified.

**Comment by ScottDaniels** [comment]
Full mirroring (not VLAN tag limited) is now implemented and can be configured using an iplex command, or by setting the proper values in the VF's config file.
