### ISSUE TITLE
[FR] Support for multiple NICs and Intel FVL-25 Fortville 

### ISSUE THREAD

**Issue by krjoshi** [att/vfd#132]
Support for multiple NICs: develop harness to dynamically detect which NIC is installed, and call appropriate PMD functions for that NIC.  

Add support for the Intel FVL-25 Fortville NIC using within the multi-NIC framework.

**Comment by ScottDaniels** [comment]
The nic-agnostic branch which supports FV25, Mellanox, and Broadcom NICs has been merged into master. Merge occurred in 12 2017.
