### ISSUE TITLE
VFd is not clearing the old MAC's list in the config properly

### ISSUE THREAD

**Issue by dhanunjaya** [att/vfd#152]
the old MAC's are still persistent and in control of VFd even though after updating the MAC's list in the config.

**Comment by ScottDaniels** [comment]
I've done a bit of testing with this and found this to be more of an edge case than it initially appears. 

If the configuration deleted, and a new config added with a different MAC, AND the guest resets its interface, the old MAC address no longer delivers packets to the application in the guest. 

However, if the application (DPDK) in the guest does not reset, the old MAC is still valid. 

Needs more testing.

**Comment by ScottDaniels** [comment]
It seems that if multicast is set true in the config file, and the test MAC address(es) used match a multicast address, they will be delivered and it will appear that the MAC isn't being cleared.  This should be tested with mcast set to false in the config file.  

Assigning to DJ to retest with mcast == false.

**Comment by ScottDaniels** [comment]
I am able to reproduce this in the outbound direction.   Inbound seems to work as desired, but when a MAC address for a guest is removed from the list the NIC does not flag packets written with the old MAC.

**Comment by ScottDaniels** [comment]
In the case where a configuration is given more than one MAC address in the list, and then one of the addresses removed, the guest is NOT able to send packets using the removed address (as expected).

If only one MAC address is given, and then removed, the guest can still continue to send traffic with that traffic as the source address after it is removed.  This may seem to be unexpected, and wrong, however the first MAC given in the list is set as the default MAC for the VF and when cleared it is removed from the white list, but it cannot be removed from being the default (the dpdk function is a set only, not a set or clear as the white list function is).  

The third case is if the guest has 'pushed' a MAC address (via ifconfig or similar) onto the VF. In this case when the list in the configuration is cleared, none of the addresses which were supplied in the old configuration can be used for sending packets.  


With the current code, I believe the behavour is as expected.

**Comment by ScottDaniels** [comment]
Closing as there have been no dissenting comments made.
