### ISSUE TITLE
Target VF id check in mirror setting is wrong

### ISSUE THREAD

**Issue by Awik84** [att/vfd#242]
The actual number of vfs (port->nvfs_config) can be bigger than the configured number
(port->num_vfs) so target id can also be bigger.

For example: PF has 16 VFs, but only vfs 13 and 14 are configured with json files and vf 13 is has mirror settings targeting vf 14. This configuration will fail since port->num_vfs = 2 and the check is target_id > port->num_vfs instead of target_id > port->nvfs_config.

**Comment by ScottDaniels** [comment]
This has been corrected in commit c5f3e0e3 (pushed into nic_agnostic).

To test:
1) Create a small number of .json VF config files for PF x,  and start VFd.

2) Create an additional VF config file, alsof for PF x, that has a mirror definition with a target that is greater than the number of VFs known to VFd (step 1), but less than the total number of VFs currently existing

3) Run 'iplex add xxx' on the config file to add the new VF to VFd's view.  Add should be successful
