### ISSUE TITLE
VF TC qshare percentage 

### ISSUE THREAD

**Issue by Awik84** [att/vfd#243]
@ScottDaniels - Not clear whether the share percentage in the VF configuration is related to the PF TC min_bw configuration.

For example: TC0 in the PF QoS cfg has min_bw of 50% of link speed. Does that mean that if VF0 has qshare configuration of 10% in TC0 it will get 5% of the link speed?
From the code it seems that VF TC configuration doesn't care of the PF configuration at all (Unless I missed something.

**Comment by ScottDaniels** [comment]
Sorry for the delayed response.... this didn't land on my radar it seems.

Yes, the TC0 would be given 5% of the overall link bandwidth.
