### ISSUE TITLE
wrong qshare array calculation

### ISSUE THREAD

**Issue by Awik84** [att/vfd#259]
in vfd_rif.c qshares array generation is wrong when no normalization is needed.
for( j = **i**; j < port->num_vfs; j++ ) {

should be

for( j = 0; j < port->num_vfs; j++ ) {

**Comment by ScottDaniels** [comment]
Corrected; thank you.

Commit 312a1c48becef342ad7ba4984b013f6153a01c83 has the correct code.  The first commit replaced  j = i with j = 1, and was fixed in the later commit. 

Changes pushed to nic_agnostic branch.
