### ISSUE TITLE
[FR] User defined MAC assignment

### ISSUE THREAD

**Issue by krjoshi** [att/vfd#34]
VFd needs to allow users to provide a MAC address for a VF. This requirement is to support nova integration where MAC is supplied by nova. The VF must use the supplied MAC address whenever the VF is created or reinitialized. However, to support VF teaming, VFd should also allow the VM to override this MAC address and change it to something else.

**Comment by ScottDaniels** [comment]
VFd now supports MAC addresses supplied by the guest/DPDK application. Addresses submitted by the rte_eth_dev_mac_addr_add() (or similar) are added to the VF's white list.   The address will be accepted provided that the total for the VF does not exceed the VF max, and the total across the PF does not exceed the PF max.   In addition, the MAC will only be allowed if it is not duplicated on the PF.
