### ISSUE TITLE
When vfid is given as string in the config, vfd is confguring vf 0.

### ISSUE THREAD

**Issue by dhanunjaya** [att/vfd#37]
Eg, "vfid": "-13"

**Comment by ScottDaniels** [comment]
Json parser didn't allow for fine grained type checking, just a missing test.  I've added fine grained checking for the primitive types (value, boolean, null) and modified the config file parser to switch the checks from !missing to !value_type  to catch this situation.   

Testing is pending.

**Comment by ScottDaniels** [comment]
Closing.  Fixed in commit 584609c84d9ca1283e18032571587916ca228d66
