### ISSUE TITLE
Number of VFs affects queue state recognition.

### ISSUE THREAD

**Issue by ScottDaniels** [att/vfd#40]
If the VFs created on a PF is less than 32, the queue checking mechanism is getting it wrong and as a result the status for a VF is likely to be incorrect and we don't detect when the queue becomes ready which potentially prevents us from 'activating' the VF.

**Comment by ScottDaniels** [comment]
I believe this has been fixed when we merged changes to use DPDK 16.11.

**Comment by krjoshi** [comment]
Resolved by move to DPDK 1611
